# ==========================================
# 1. Configuración de Base de Datos (PostgreSQL)
# ==========================================
quarkus.datasource.db-kind=postgresql
# Cambia localhost, el puerto y el nombre de la BD según tu entorno
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dbposweb
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# ==========================================
# 2. Configuración de Hibernate ORM (Panache)
# ==========================================
# Desactivamos la creación automática de tablas de Hibernate porque usaremos Flyway
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8080
# ==========================================
# 3. Configuración de Flyway
# ==========================================
# Ejecuta las migraciones automáticamente al iniciar la app
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1 

# ==========================================
# 4. Configuración de JWT (Base)
# ==========================================
# Define quién emite el token (lo usaremos más adelante al asegurar endpoints)
mp.jwt.verify.issuer=https://mi-dominio.com/issuer